### ISSUE TITLE
Bad Reconstruction

### ISSUE THREAD

**Issue by jzubizarreta** [FangGet/lsd_slam_no_ros_pangolin#1]
Hi,

I have already compiled your LSD-SLAM version with Pangolin. It is working but i am getting bad reconstructions. What I mean with "bad" is that the pointcloud contains too much noise and many points seem to be bad triangulated (forming the typical cone of points). My results are far away from the original videos.

 I am working with an HP Webcam at 640x480. It is calibrated with the FOV-model correctly (PTAM model). 

Are you getting the same results? Otherwise, could you tell me how to improve them?

Thanks in advance,

Jon

**Comment by FangGet** [comment]
try open following camera option and resee the result

**Comment by jzubizarreta** [comment]
That option only makes the user watch the scene from the camera, but the reconstruction is still bad :(
Any other idea?

**Comment by FangGet** [comment]
have you tested dataset?

**Comment by jzubizarreta** [comment]
I have tried the desk dataset and my reconstruction is very noise compared to the pointcloud that they get.
Have you tried that dataset? Have you change any parameter?

Thanks for answering that fast :)

**Comment by FangGet** [comment]
I have tried a TUM official dataset given by LSD-SLAM and got a similar result as they demonstrated

**Comment by jzubizarreta** [comment]
Mmmm... i don't know then. Have you done any parameter tunning? Do you have openFabMap activated?
Could you send me images of your reconstruction so I can compare them with mines? Thanks in advance.

**Comment by baclee** [comment]
I've got the same problem.
Trying to figure out why.

**Comment by FangGet** [comment]
please show your result snapshot.
btw, i did not use openFabMap
