### ISSUE TITLE
test tum and EuRoC dataset

### ISSUE THREAD

**Issue by pisuto** [FangGet/lsd_slam_no_ros_pangolin#3]
Hi, FangGet

I have a problem that tracking is lost after several frames when running your code and testing tum and  EuRoC dataset.
tum(rgbd_dataset_freiburg2_desk):
![2019-01-28 16 52 15](https://user-images.githubusercontent.com/24860995/51824442-3e6f0e00-231d-11e9-8eb7-2cfabb5377af.png)
`0.813920 1.085432 0.508034 0.520212 0
640 480
crop
640 480`
EuRoC(V1_01_easy):
![2019-01-28 16 53 03](https://user-images.githubusercontent.com/24860995/51824456-49c23980-231d-11e9-9b05-78efcd0c8cda.png)
`0.609912 0.952700 0.488318 0.517448 0
752 480
full
752 480`
they all lost tracking, and below it's camera calibration.

Do you have any idea about this? Except viewer, do you change any code so that this problem occurs?

**Comment by FangGet** [comment]
nope, I only removed ros, added pangolin for viewer and two samples for successfully running of dataset and live camera, no kernel code changged.

**Comment by OTzGitz23** [comment]
Hello! Did you solve this problem?
