### ISSUE TITLE
/usr/bin/ld: can not found  -lcsparse

### ISSUE THREAD

**Issue by OTzGitz23** [FangGet/lsd_slam_no_ros_pangolin#4]
Scanning dependencies of target lsd_slam_core
[  3%] Building CXX object CMakeFiles/lsd_slam_core.dir/src/GlobalMapping/KeyFrameGraph.cpp.o
[  7%] Linking CXX shared library ../lib/liblsd_slam_core.so
/usr/bin/ld: can not found  -lcsparse
collect2: error: ld returned 1 exit status
CMakeFiles/lsd_slam_core.dir/build.make:413: recipe for target '../lib/liblsd_slam_core.so' failed
make[3]: *** [../lib/liblsd_slam_core.so] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/lsd_slam_core.dir/all' failed
make[2]: *** [CMakeFiles/lsd_slam_core.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/dataset_lsd_slam.dir/rule' failed
make[1]: *** [CMakeFiles/dataset_lsd_slam.dir/rule] Error 2
Makefile:118: recipe for target 'dataset_lsd_slam' failed
make: *** [dataset_lsd_slam] Error 2

**Comment by FangGet** [comment]
Try substitute FindPackage(Cparse ) with suitesparse if you have install suitesparse  on your ubuntu, or so, just install suitesparse or csparse first.

**Comment by OTzGitz23** [comment]
> Try substitute FindPackage(Cparse ) with suitesparse if you have install suitesparse on your ubuntu, or so, just install suitesparse or csparse first.

I have installed suitesprase,but is same error

libsuitesparse-dev is the latest version (1:5.1.2-2)。

**Comment by FangGet** [comment]
Well, your csparse library linkage encounters problem, try mannually add lib***csparse.so at CMakeLists.txt target_link_library.

I cloned this repo, builded it successfully with one try(some trivial revise for gcc 5.4), and no library link error encountered.

**Comment by OTzGitz23** [comment]
> Well, your csparse library linkage encounters problem, try mannually add lib***csparse.so at CMakeLists.txt target_link_library.
> 
> I cloned this repo, builded it successfully with one try(some trivial revise for gcc 5.4), and no library link error encountered.

Thank you. I reinstalled the old version of g2o and pangolin, and the build went smoothly.Then，I will learnning use it >-<
