### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by OTzGitz23** [FangGet/lsd_slam_no_ros_pangolin#5]

**Comment by FangGet** [comment]
see main_on_images.cpp，you need config file and
 dataset directory

**Comment by OTzGitz23** [comment]
> see main_on_images.cpp，you need config file and
> dataset directory

你好，我想跑KITTI数据集，不明白命令行参数和calib文件怎么填，能告知一下吗？

**Comment by FangGet** [comment]
example usage:
./dataset_lsd_slam  ../calib/camera.txt ../data/TUM_01/
